; extensions.conf - the Asterisk dial plan
;
; Static extension configuration file, used by
; the pbx_config module. This is where you configure all your
; inbound and outbound calls in Asterisk.
;
; This configuration file is reloaded
; - With the "dialplan reload" command in the CLI
; - With the "reload" command (that reloads everything) in the CLI

;
; The "General" category is for certain variables.
;
[general]
;
; If static is set to no, or omitted, then the pbx_config will rewrite
; this file when extensions are modified.  Rem>ember that all comments
; made in the file will be lost when that happens.
;
; XXX Not yet implemented XXX
;
static=yes
;
; if static=yes and writeprotect=no, you can save dialplan by
; CLI command "dialplan save" too
;
writeprotect=no
;
clearglobalvars=no

[globals]
CONSOLE=Console/dsp				; Console interface for demo
;CONSOLE=DAHDI/1
[default]
;
; By default we include the demo.  In a production system, you
; probably don't want to have the demo there.
;
include => demo

[from-external]
exten => 123,1,NoOp(Dialing 123)
	same => n,Dial(PJSIP/trunk-loopback-ip/sip:123@127.0.0.1:5666)
	same => n,Wait()
	same => n,NoOP(Hanguping)
	same => n,Hangup()


exten => playback,1,NoOp(Dialing uas)
	same => n,Playback(demo-instruct)
	same => n,Hangup()

