; Basic UDP transport
;
[transport-udp-loopback]
type=transport
protocol=udp    ;udp,tcp,tls,ws,wss,flow
bind=127.0.0.1:5060

[trunk-loopback-ip]
type=endpoint
transport=transport-udp-loopback
context=from-external
disallow=all
allow=ulaw,alaw
dtmf_mode=auto
force_rport=yes    ;It's a good idea to read the configuration help for each
direct_media=no    ;of these options.
ice_support=no

[trunk-loopback-ip]
type=identify
endpoint=trunk-loopback-ip
match=127.0.0.0/24
match=192.168.0.0/16



